name: air-quality-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      # Step 1: Checkout latest repository code
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures the latest commit is used

      # Step 2: Setup Python environment
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # Step 3: Install dependencies
      - name: install python packages
        run: |
          cd notebooks/ch03
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debug notebook directory (optional)
      - name: Debug directory structure
        run: |
          ls -R notebooks/ch03

      # Step 5: Execute workflows
      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          cd notebooks/ch03
          jupyter nbconvert --to notebook --execute 2_air_quality_feature_pipeline.ipynb
          jupyter nbconvert --to notebook --execute 4_air_quality_batch_inference.ipynb

      # Step 6: Publish updates to GitHub Pages
      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Air Quality Dashboard published"
          commit_options: '--no-verify --signoff'
          file_pattern: 'docs/air-quality/assets/img/* docs/_includes/*'
          repository: .
          status_options: '--untracked-files=no'
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
          push_options: '--force'
